# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=10)),
                ('measurement1', models.CharField(max_length=17)),
                ('measurement2', models.CharField(max_length=5)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
